### ISSUE TITLE
Unnecessary using pointer receiver in Error type

### ISSUE THREAD

**Issue by alehano** [rethinkdb/rethinkdb-go#242]
Why do you use pointer receiver in func (e *Error) Error() string? It's not necessary.
Because of that I got error while error assertion:

```
        if esErr, ok := err.(elastic.Error); ok && esErr.Status == 404 {
        }
```

> elastic.Error does not implement error (Error method has pointer receiver)

And I have to do this instead:

```
        if esErr, ok := err.(*elastic.Error); ok && esErr.Status == 404 {
        }
```

Which is less obvious and uglier.

But change this will brake backward compatibility.

**Comment by dancannon** [comment]
I agree with your point that the pointer receiver is a bit uglier however as you mention this change would break backwards compatibility. I will mark this issue as on hold and revisit when working on 2.0, unfortunately I dont have an ETA for this just yet.

**Comment by dancannon** [comment]
Just started looking into this and realised that this issue was probably created on the wrong project. Sorry for not looking into this properly earlier!

**Comment by alehano** [comment]
Yeah, I'm sorry too.
